[project]
name = "just_test"
version = "102.1"
description = "Just a test"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib==3.11.0",
    "nltk==3.10.0",
    "numpy==2.5.1",
    "pandas==3.0.3",
    "tqdm==4.68.4",
]

[dependency-groups]
dev = [
    "pylint==4.0.6",
    "pytest==9.1.1",
]
